name: push

on:
  push:
    pull-request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: set up JDK 17
         uses: actions/setup-java@v1
         with:
            java-version: 17
       - name: Start
         run: |
            echo 'AliceGame'
       - name: Maven Package
         run: mvn clean install
                - name: Test Coverage
                uses: codecov/codecov-action@v1
                with:
                  token: ${{ secrets.CODECOV_TOKEN }}
